config/routes.rb
Rails.application.routes.draw do
 

  resources :responses
  devise_for :users
  resources :users 
  
  

  # resources :surveys 
  
  # resources :questions
  # resources :answers
  # resources :responses

  resources :ads
  resources :abouts
  resources :contacts
  resources :forms
  resources :pages

  get '/search' =>  'home#search'

  get '/contact' => 'home#contact'

  get '/about' =>  'home#about'
  get '/partners' =>  'home#partner'

  get '/lk' =>  'home#lk'
  get '/vote' =>  'home#vote'
  get '/admin_category' =>  'home#page'

  get '/moderators' =>  'home#moderators'
  get '/admins' =>  'home#admins'

  
  resources :categories
  
  resources :petitions do
    member do
      put 'vote'
      put 'st'
      put 'add'
    end
  end
  get '/categories/:category_id/:id' => 'petitions#categories', as: :category_petitions
  root 'home#index'
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  #assiciations
  belongs_to :status
  belongs_to :vote
  belongs_to :like
  belongs_to :category
  belongs_to :user

  has_many :responses, dependent: :destroy
  has_many :users, through: :responses
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: lambda { |a| a[:text].blank? }, allow_destroy: true

  #Callbacks
  before_create :vot
  before_create :add
  before_save :st
  before_create :assign_slug
  before_update :assign_slug
  before_destroy :des

  #Methods
  def des
    self.foto = nil
    self.save
  end
  def vot
    self.vote = Vote.create
  end
  def add
    self.like = Like.create
  end
  def st
    self.status = Status.find(1) if self.status.nil?
  end

  # def slug
  #   name.mb_chars.downcase.gsub(" ", "-").to_s  
  # end
  def assign_slug
    self.slug = self.name.to_slug_param(locale: :ru)
  end

  def to_param 
   "#{slug}"
 end

 has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
 validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/


 def self.search(search)
  if search
    self.where("name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ?", "%#{search.mb_chars.capitalize.to_s}%", "%#{search.mb_chars.to_s}%", "%#{search.mb_chars.upcase.to_s}%", "%#{search.mb_chars.downcase.to_s}%" )
  else
    self.all
  end
end
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :petition
	has_many :response_questions, dependent: :destroy
	has_many :responses, through: :response_questions
	has_many :answers, dependent: :destroy
	accepts_nested_attributes_for :answers, reject_if: lambda { |a| a[:text].blank? }, allow_destroy: true

end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_filter :authenticate_user!,only: [:new, :edit, :index]
  before_action :set_petition, only: [:show, :edit, :update, :destroy, :vote, :st, :add, :categories]
  layout 'admin', only: [:new,:edit, :index]
  # GET /petitions
  # GET /petitions.json
  def index
    if current_user.role_id ==1 or current_user.role_id == 3
      @petitions = Petition.all.page(params[:page]).per(10)
    else
      @petitions = Petition.where(user:current_user).page(params[:page]).per(10)
    end


  end

  def vote
    @petition.vote.users << current_user if @petition.user != current_user or current_user.role_id == [1,3]
    if @petition.save
      redirect_to @petition
    end
  end
  def add
    @petition.like.users << current_user if @petition.user != current_user or current_user.role_id == [1,3]
    respond_to do |format|
      format.html {redirect_to :back, notice: "Liked!"}
      format.js
    end

  end
  def st

    @petition.status = Status.find(2)
    if @petition.save
      redirect_to petitions_path
    end

  end
  # GET /petitions/1
  # GET /petitions/1.json
  def show

    if @petition.category.name == "Опросы"
      @title = "Нравится"
      @untitle = "Понравилось"
      @all = "Всего понравилось:"
      else
      @title = "Проголосовать"
      @untitle = "Проголосовано"
      @all = "Всего голосов:"
    end


  end
  def categories

    if @petition.category.name == "Опросы"
      @title = "Нравится"
      @untitle = "Понравилось"
      @all = "Всего понравилось:"
      else
      @title = "Проголосовать"
      @untitle = "Проголосовано"
      @all = "Всего голосов:"
    end


  end

  # GET /petitions/new
  def new
    @petition = Petition.new
  end

  # GET /petitions/1/edit
  def edit
  end

  # POST /petitions
  # POST /petitions.json
  def create
    @petition = Petition.new(petition_params)
    @petition.user_id = current_user.id
    respond_to do |format|
      if @petition.save
        format.html { redirect_to @petition, notice: 'Ваша публикация создана' }
        format.json { render :show, status: :created, location: @petition }
      else
        format.html { render :new }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petitions/1
  # PATCH/PUT /petitions/1.json
  def update
    respond_to do |format|
      if @petition.update(petition_params)
        format.html { redirect_to petitions_path, notice: 'Данные Обновлены' }
        format.json { render :show, status: :ok, location: @petition }
      else
        format.html { render :edit }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petitions/1
  # DELETE /petitions/1.json
  def destroy
    @petition.destroy
    respond_to do |format|
      format.html { redirect_to petitions_url, notice: 'Публикация Удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petition
      @petition = Petition.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petition_params
      params.require(:petition).permit(:from,:name, :text, :status_id, :vote_id, :like_id, :category_id, :user_id, :foto, questions_attributes: [:id, :text,:active, :status ,:_destoy, answers_attributes:[:id, :text, :_destroy]])
    end
  end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/views/petitions/_answer_fields.html.erb
<fieldset>
	<%= f.label :text, "Ответ" %>
	<%= f.text_field :text, class:"form-control" %>
	<p>
	<%= f.hidden_field :_destroy %>
	
	<%= link_to "Удалить ответ", '#', class: "remove_fields" %>
	</p>
</fieldset>

app/views/petitions/_form.html.erb
<%= form_for(@petition) do |f| %>
<% if @petition.errors.any? %>
<div id="error_explanation">
 <h2><%= pluralize(@petition.errors.count, "error") %> prohibited this petition from being saved:</h2>

 <ul>
   <% @petition.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>
<fieldset>
 <legend>Данные</legend>

 <div class="form-group">
   <label>Изображение для публикации</label>
   <div>
    <%= image_tag @petition.foto.url(:thumb) %>
  </div>
  <br>

  <%= f.file_field :foto, id: "pictureInput" %> 
  <div id="target">
   предпросмотр изображения
 </div>
 <script>
   $(function() {
    $('#pictureInput').on('change', function(event) {
      var files = event.target.files;
      var image = files[0]
      var reader = new FileReader();
      reader.onload = function(file) {
        var img = new Image();
        console.log(file);
        img.src = file.target.result;
        img.width = 200
        img.height =100
        $('#target').html(img);
      }
      reader.readAsDataURL(image);
      console.log(files);
    });
  });
</script>
</div><!-- /.form-group -->
<div class="form-group">
 <label>Выберите категорию</label><br>

 <%#= f.collection_radio_buttons :category_id, Category.all, :id, :name , required: true %>
  <% Category.all.each do |category| %>
  <div>
    <%= f.radio_button :category_id, category.id %>
    <%= f.label :category_id, category.name %>
    </div>
  <% end %>


</div><!-- /.form-group -->

<div class="form-group">
 <label>Название</label>
 <%= f.text_field :name, class:"form-control", required: true, pattern: "^[A-Za-zа-яёА-ЯЁ0-9\s\-]+$",
 oninvalid: "setCustomValidity('Спец. символы запрещены, используйте только буквы')",
 oninput:"setCustomValidity('')" 
 %>
</div><!-- /.form-group -->
<div class="form-group">
 <label>Кому</label>
 <%= f.text_field :from, class:"form-control", required: true, placeholder: "Кому адресована публикация" %>
</div><!-- /.form-group -->

<div class="form-group">
 <label>Описание</label>
 <%= f.text_area :text, class:"form-control", required: true, rows:"6", id: "ckeditor"  %>
 <script>
  $('#ckeditor').ckeditor({
  });
</script>
</div><!-- /.form-group -->
<div class="form-group">
  <h5>Если вы желаете создать опрос добавьте вопрос и к нему варианты ответа:</h5>
  <%= f.fields_for :questions do |builder| %>
   <%= render "question_fields", f: builder %>
   <% end %>
   <!-- </div> -->
   <p><%= link_to_add_fields 'Добавить вопрос', f, :questions %></p>
</div>

</fieldset>



<div class="center">
  <%= f.submit "Сохранить", class:"btn btn-primary btn-large" %>
</div><!-- /.center -->
</form>
<% end %>

app/views/petitions/_question_fields.html.erb
<!-- <div class="col-md-10"> -->
<fieldset >

	<%= f.label :text, "Вопрос" %>
	<%= f.text_field :text, class:"form-control" %>
	
	<%= f.label :status, "Много ответов" %>

	<%= f.check_box :status, {}, 'true', 'false' %>
	<%= f.label :active, "Свой ответ" %>
	<%= f.check_box :active, {}, 'true', 'false' %>
	<p>
	<%= f.hidden_field :_destroy %>
	<%= link_to "Удалить Вопрос", '#', class: "remove_fields" %>
	</p>
<!-- </div> -->
	<!-- <div class="container"> -->
<%= f.fields_for :answers do |builder| %>
<%= render 'answer_fields', :f => builder %>
<% end %>

<!-- <br> -->
<%= link_to_add_fields "Добавить ответ", f, :answers %>
	<!-- </div> --></fieldset>

app/views/petitions/_response.html.erb
<%= form_for Response.new do |f| %>
<fieldset>
	<%= hidden_field_tag "response[petition_id]", petition.id %>
<%#= f.fields_for :response_questions do |builder|  %>
<% petition.questions.each_with_index do |question, index| %>
		<%= hidden_field_tag "response[response_questions_attributes][#{index}][question_id]", question.id %>
		<%= question.text %>
		<fieldset>
		<% question.answers.each do |answer| %>

		<p>
		<% if question.status == true %>
			<%= check_box_tag "response[response_questions_attributes][#{index}][answer_ids][]", answer.id %>

			<%else%>
			<%= radio_button_tag "response[response_questions_attributes][#{index}][answer_ids][]", answer.id %>
		<% end -%>
		<%= answer.text %>
		
		</p>
		<% end -%>
		<% if question.active == true %>
		Свой ответ:
		<%#= check_box_tag :status %>
			<%= text_area_tag "response[response_questions_attributes][#{index}][text]" %>
		<% end %>
		</fieldset>

<% end -%>
<%# end -%>
</fieldset>
<% if user_signed_in?  %>
<%= f.submit "Сохранить" , class:"btn btn-primary btn-large" %>
<% else %>
<%= link_to "Сохранить", new_user_session_path, class:"btn btn-primary btn-large"  %>
<% end -%>
<% end -%>

app/views/petitions/_result.html.erb
<fieldset>
	Проголосовало:
	<%= petition.responses.count %>
	<% petition.questions.each do |question| %>
	<fieldset>
		<%= question.text %>
		<br>

		<% question.answers.each do |answer| %>
		<fieldset>
			<%= answer.text %>
			<br>
			<progress value="<%= answer.response_questions.count %>" max="<%= User.where.not(role_id: 1).count %>"></progress>
			
			
			<p>
			<%= "Голосов:#{answer.response_questions.count}" %>
			</p>

			<% answer.response_questions.each do |r| %>
				<% if current_user.admin? %>
				<%= link_to r.response.user.email, edit_user_path(r.response.user) %>
				<% end %>
			<% end %>
		</fieldset>
		<% end %>
		
		<% if current_user.admin?   %>
	
		<%= "Ответы:" if question.active == true %>
			<% ResponseQuestion.where(question_id: question.id).each do |q|  %>
			<p>
<a  data-toggle="collapse" href="#collapse<%= q.id %>" aria-expanded="false" aria-controls="collapse">
    <%= q.response.user.name unless q.text.blank? %>
  <%= q.response.user.surname unless q.text.blank? %>
</a>
<div class="collapse" id="collapse<%=q.id%>">
  <!-- <div class="well"> -->
    <%= q.text unless q.text.blank?%>
  <!-- </div> -->
</div>
			
				</p>
			<% end %>
		
		<% elsif petition.user == current_user %>
			<%= "Ответы:" if question.active == true %>
			<% ResponseQuestion.where(question_id: question.id).each do |q|  %>
			<p>

    <%= q.text unless q.text.blank?%>
			
				</p>
			<% end %>

		<% else %>
				<p>
			<%= "Мой Ответ: #{ResponseQuestion.find_by(question_id: question.id, response_id: Response.find_by(user: current_user, petition_id: petition.id).id ).text}" unless ResponseQuestion.find_by(question_id: question.id, response_id: Response.find_by(user_id: current_user.id, petition_id: petition.id).id ).text.blank? %>
			</p>
		<% end %>
		
	</fieldset>
	<%#= response.user.email %>

	<% end %>


</fieldset>

app/views/petitions/_widget.html.erb
<div class="widget">
                <h2 class="widgettitle">Последние публикации</h2>

                <div class="cards-small-wrapper">
                  <% Petition.where(status: 2).last(4).reverse_each do |p| %>
                  <div class="card-small">
                    <div class="card-small-image">
                      <a href="<%= category_petitions_path(p.category, p) %>" style="background-image: url('<%= image_path p.foto.url %>');"></a>
                    </div><!-- /.card-small-image -->

                    <div class="card-small-content">
                      <h3><a href="<%= category_petitions_path(p.category, p) %>"><%= truncate(p.name, length: 20) %></a></h3>
                      <h4><a href="<%= category_path(p.category) %>"><%= p.category.name %></a></h4>
                    </div><!-- /.card-small-content -->
                  </div><!-- /.card-small -->
                  <% end %>

                </div><!-- /.cards-small-wrapper -->
              </div><!-- /.widget -->

app/views/petitions/add.js.erb
window.location.reload();

app/views/petitions/categories.html.erb
<div class="main-wrapper">
 <div class="main">
   <div class="main-inner">


     <div class="content">
       <div class="content-title">
         <div class="container">
           <h1><%= @petition.name %></h1>

           <ul class="breadcrumb">
             <li>  <%= render_breadcrumbs :separator => '<i class="md-icon">keyboard_arrow_right</i>' %></li>




           </ul><!-- /.breadcrumb -->
         </div><!-- /.container -->
       </div><!-- /.content-title -->



       <div class="container">
         <div class="row">
           <div class="col-md-8 col-lg-9">
             <div class="push-top-bottom">
               <div class="listing-detail">

                 <div class="gallery-item" style="background-image: url('<%= image_path @petition.foto.url %>');">

                 </div><!-- /.gallery-item -->



                 <!-- <h2><%#= @petition.name %></h2> -->
                 <br>
                 <p>
                  <%= @petition.text.html_safe %>
                </p>
                <p>
                  Кому:<%= @petition.from %>
                </p>





                <h2>Поделиться:</h2>

                <div class="social-share-buttons">
                  <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
                  <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
                  <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,lj,pocket,tumblr,viber,whatsapp" data-title="<%= @petition.name %>" data-description="<%= @petition.text %>" data-image="<%= image_url(@petition.foto) %>"></div>
                </div>





              </div><!-- /.listing-detail -->
            </div><!-- /.push-top-bottom -->
          </div><!-- /.col-sm-9 -->

          <div class="col-md-4 col-lg-3">
           <div class="sidebar">

            <div class="widget">
              <h2 class="widgettitle">Всего Голосов <%= @petition.vote.users.count %></h2>


              <div class="overview" id="vote">

               <% if @petition.vote.users.include?(current_user)  %>
               <button type="submit" class="btn btn-primary btn-block btn-large" disabled="disabled">Проголосовано</button>
               <% else %>
               <% if user_signed_in? %>
               <%= link_to 'Проголосовать', { controller: :petitions, action: :vote }, { method: :put , class: "btn btn-primary btn-block btn-large"} if @petition.user != current_user %>

               <% else %>
               <%= link_to 'Проголосовать', new_user_session_path , class:"btn btn-primary btn-block btn-large" %>

               <% end %>
               <% end %>

             </div><!-- /.overview -->

           </div><!-- /.widget -->
           <%= render 'petitions/widget' %>
           <%= render 'categories/widget' %>


         </div><!-- /.sidebar -->
       </div><!-- /.col-* -->
     </div><!-- /.row -->
   </div><!-- /.container-->
 </div><!-- /.content -->
</div><!-- /.main-inner -->
</div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/petitions/edit.html.erb
<div class="admin-content">
			<div class="container-fluid">
				<div class="admin-title">


	<h1>Редактирование</h1>

	<ul class="breadcrumb">


	</ul><!-- /.breadcrumb -->
</div><!-- /.admin-title -->

<div class="admin-box">


		<div class="row">

<%= render 'form' %>
</div><!-- /.row -->





</div><!-- /.admin-box -->
  </div><!-- /.container-fluid -->
</div><!-- /.admin-content -->

app/views/petitions/index.html.erb
<div class="container-fluid">
<div class="admin-title">
	<h1>Публикации</h1>
<ul class="breadcrumb">

</ul>
</div>
</div>


<div class="admin-box no-padding">
	<table class="table small-header">
		<thead>
			<tr>
				<th class="min-width">Фото</th>
				<th>Название</th>
				<th>Категория</th>
				<th>Автор</th>
				<th>Статус</th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
      <% @petitions.reverse_each do |p| %>
				<tr>

					<td class="min-width"><%= image_tag p.foto.url(:thumb) , class: "backend-table-thumb "%></td>
					<td><%= p.name.truncate(30) %></td>
					<td><%= p.category.name %></td>
					<td><%= p.user.name %> <%= p.user.surname %></td>
						<td><%= p.status.name %>

						<% if current_user.role_id == 1 or current_user.role_id == 3 %>
							
							<%= form_for p do |form| %>
								<%= form.check_box :status_id , {onchange: "this.form.submit()"}, 2 , 1 %>

							<% end -%>
							<%# if p.status_id == 1 %>
							<%#= link_to st_petition_path(p), { method: :put, id: 'push' }  do  %>
							<!-- <i class="md-icon">check</i> -->
							<%# end %>
							<%# end %>



							<% end %>

						</td>
					<td>
						</td>
						<td>
            <%= link_to category_petitions_path(p.category, p) do %>
            <i class="md-icon">remove_red_eye</i>
            <% end %>
				
				<% if current_user.role_id != 3 %>
				<% if p.vote.users.count == 0 and p.responses.count == 0 %>
            <%= link_to edit_petition_path(p) do %>
            <i class="md-icon">edit</i>
            <% end %>
            <% end %>

						<%= link_to p, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="md-icon">delete</i>
            <% end %>
            <% end %>



					</td>
				</tr>
        <% end %>
      </tbody>
</table>

</div><!-- /.admin-box -->

<nav class="pagination-wrapper">

	<%= paginate @petitions %>

</nav>

app/views/petitions/new.html.erb
<div class="admin-content">
			<div class="container-fluid">
				<div class="admin-title">


	<h1>Создание новой петиции</h1>

	<ul class="breadcrumb">


	</ul><!-- /.breadcrumb -->
</div><!-- /.admin-title -->

<div class="admin-box">


		<div class="row">

<%= render 'form' %>
</div><!-- /.row -->





</div><!-- /.admin-box -->
  </div><!-- /.container-fluid -->
</div><!-- /.admin-content -->

app/views/petitions/show.html.erb
<div class="main-wrapper">
 <div class="main">
   <div class="main-inner">


     <div class="content">
       <div class="content-title">
         <div class="container">
           <h1><%= @petition.name %></h1>

           <ul class="breadcrumb">
             <li>  <%= render_breadcrumbs :separator => '<i class="md-icon">keyboard_arrow_right</i>' %></li>




           </ul><!-- /.breadcrumb -->
         </div><!-- /.container -->
       </div><!-- /.content-title -->



       <div class="container">
         <div class="row">
           <div class="col-md-8 col-lg-9">
             <div class="push-top-bottom">
               <div class="listing-detail">

                 <div class="gallery-item" style="background-image: url('<%= image_path @petition.foto.url %>');">

                 </div><!-- /.gallery-item -->



                 <!-- <h2><%#= @petition.name %></h2> -->
                 <br>
                 <p>
                  <%= @petition.text.html_safe %>
                </p>




                <% unless  @petition.questions.blank? %>
                <% if user_signed_in? and current_user.admin? %>
                <%= render 'result', petition: @petition %>

                <% else %>
                

                <% if  @petition.users.include? current_user or @petition.user == current_user %>

                <%= render 'result', petition: @petition %>
                <% else %>
                <%= render 'response', petition: @petition %>
                <% end %>
                <% end %>
                <% end %>
                <div class="to_whom">
                  Кому: <%= @petition.from %>
                </div>
                <h2>Поделиться:</h2>
                <div class="social-share-buttons">
                  <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
                  <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
                  <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,lj,pocket,tumblr,viber,whatsapp" data-title="<%= @petition.name %>" data-description="<%= @petition.text %>" data-image="<%= image_url(@petition.foto) %>"></div>
                </div>





              </div><!-- /.listing-detail -->
            </div><!-- /.push-top-bottom -->
          </div><!-- /.col-sm-9 -->

          <div class="col-md-4 col-lg-3">
           <div class="sidebar">

            <div class="widget">
              <h2 class="widgettitle"><%= @all %> <%= @petition.vote.users.count %></h2>


              <div class="overview" id="vote">



               <% if @petition.vote.users.include?(current_user)  %>
               <button type="submit" class="btn btn-primary btn-block btn-large" disabled="disabled"><%= @untitle %></button>
               <% else %>
               <% if user_signed_in? %>
               <%= link_to "#{@title}", { controller: :petitions, action: :vote }, { method: :put , class: "btn btn-primary btn-block btn-large"} if @petition.user != current_user  %>

               <% else %>
               <%= link_to "#{@title}", new_user_session_path , class:"btn btn-primary btn-block btn-large" %>

               <% end %>
               <% end %>



             </div><!-- /.overview -->
           </div><!-- /.widget -->
           <%= render 'petitions/widget' %>
           <%= render 'categories/widget' %>


         </div><!-- /.sidebar -->
       </div><!-- /.col-* -->
     </div><!-- /.row -->
   </div><!-- /.container-->
 </div><!-- /.content -->
</div><!-- /.main-inner -->
</div><!-- /.main -->
</div><!-- /.main-wrapper -->