config/routes.rb
Rails.application.routes.draw do
 

  resources :responses
  devise_for :users
  resources :users 
  
  

  # resources :surveys 
  
  # resources :questions
  # resources :answers
  # resources :responses

  resources :ads
  resources :abouts
  resources :contacts
  resources :forms
  resources :pages

  get '/search' =>  'home#search'

  get '/contact' => 'home#contact'

  get '/about' =>  'home#about'
  get '/partners' =>  'home#partner'

  get '/lk' =>  'home#lk'
  get '/vote' =>  'home#vote'
  get '/admin_category' =>  'home#page'

  get '/moderators' =>  'home#moderators'
  get '/admins' =>  'home#admins'

  
  resources :categories
  
  resources :petitions do
    member do
      put 'vote'
      put 'st'
      put 'add'
    end
  end
  get '/categories/:category_id/:id' => 'petitions#categories', as: :category_petitions
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, only: [:lk,:vote,:admin_category, :admins, :moderators]
  layout 'admin', only:[:lk,:vote,:page, :admins, :moderators]
  def index
  end

  def search

        @petitions = Petition.where(status_id: 2).search(params[:search]).page(params[:page]).per(10)

        home
        add_breadcrumb "Поиск"
  end

  def contact
  end

  def about
  end
  def partner
    @partner = Page.find_by(name: "Партнёры")
  end
  def page
    @categories = Category.all.page(params[:page]).per(10)
  end

  def lk
  end
  def vote
    @petitions = Petition.where(vote: current_user.vote).page(params[:page]).per(10)

  end
  
  before_action :super_admin?, only: [:admins, :moderators]
  # GET /users
  # GET /users.json
  def super_admin?
    unless current_user.id == 2
      redirect_to petitions_path
    end
  end



  def admins

    @users = User.where(role_id: 1).where.not(id: 2).page(params[:page]).per(10)
    home
    add_breadcrumb "Администраторы", :admins_path
  end

  def moderators
   @users = User.where(role_id: 3).page(params[:page]).per(10)
   home
   add_breadcrumb "Модераторы", :moderators_path
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_error.html.erb
<center>
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>
</center>

app/views/home/about.html.erb
<div class="main-wrapper">
  <div class="main">
    <div class="main-inner">

      <div class="content-title">
        <div class="container">
          <h1>О проекте</h1>
          <div class="social-share-about">
            <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
            <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
            <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,lj,pocket,tumblr,viber,whatsapp" data-title="О проекте" data-description="<%= simple_format(About.last.text) %>"></div>
          </div>
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <i class="md-icon">keyboard_arrow_right</i></li>


            <li class="active">О проекте</li>

          </ul><!-- /.breadcrumb -->
        </div><!-- /.container -->
      </div><!-- /.content-title -->


      <div class="container">
        <div class="row">
          <div class="col-md-8 col-lg-9">
            <div class="content">
              <div class="container push-top-bottom">
                <div class="post-detail">
                  <%= About.last.text.html_safe %>

                  <div class="">
                    <form method="post" action="">
                      <div class="row">
                        <div class="col-sm-4">
                        </div><!-- /.col-* -->

                        <div class="col-sm-4">
                        </div><!-- /.col-* -->
                      </div><!-- /.row -->

                    </form>
                  </div><!-- /.comment-create -->
                </div><!-- /.post-detail -->
              </div><!-- /.container -->
            </div><!-- /.content -->
          </div><!-- /.col-* -->

          <div class="col-md-4 col-lg-3">
            <div class="sidebar">
            <%= render 'petitions/widget' %>


              <div class="widget">
                <h2 class="widgettitle">Навигация</h2>

                <ul class="menu nav nav-stacked">
                  <li class="nav-item">
                    <a href="/" class="nav-link">Главная</a>
                  </li>

                  <li class="nav-item">
                    <a href="/categories" class="nav-link">Категории</a>
                  </li>

                  <li class="nav-item">
                    <a href="/contact" class="nav-link">Контакты</a>
                  </li>

                  <li class="nav-item">
                    <a href="/about" class="nav-link">О проекте</a>
                  </li>
                </ul><!-- /.nav -->
              </div><!-- /.widget -->
            </div><!-- /.sidebar -->
          </div><!-- /.col-* -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /.main-inner -->
  </div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/home/admins.html.erb
<div class="container-fluid">
<div class="admin-title">
	<h1>Администраторы</h1>
<ul class="breadcrumb">
	<%= render_breadcrumbs :separator => '<i class="md-icon">keyboard_arrow_right</i>' %>
</ul>
</div>
</div>


<div class="admin-box no-padding">
	<table class="table small-header" id="table" >
		<thead>
			<tr>
				<th>Фото</th>
				<th>Роль</th>
				<th>Имя</th>
				<th>Фамилия</th>
				<th>Почта</th>
				<th>Телефон</th>
				<th>Дата Регистрации</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
        <% @users.reverse_each do |u| %>
				<tr>
					<td class="min-width">
						<div class="user-avatar">
							<%= image_tag u.foto.url  %>
						</div><!-- /.user-avatar -->
					</td>
					<td><%= u.role.name.first %></td>
					<td><%= u.name %></td>
					<td><%= u.father_name %></td>
					<td><%= u.email %></td>
					<td><%= u.tel %></td>
					<td><%= u.created_at.to_date %></td>

					<td class="min-width">
            <%= link_to  edit_user_path(u) do %>
            <i class="md-icon">edit</i>
            <% end %>
            <%= link_to  u, method: :delete, data: { confirm: 'Are you sure?' }   do %>
            <i class="md-icon">delete</i>
            <% end %>

					</td>
				</tr>
<% end %>

		</tbody>
	</table><!-- /.table -->
	<nav class="pagination-wrapper">

	<%= paginate @users %>

</nav>

</div><!-- /.admin-box -->

app/views/home/contact.html.erb
<div class="main-wrapper">
  <div class="main">
    <div class="main-inner">

      <div class="content-title">
        <div class="container">
          <h1>Контакты</h1>

          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <i class="md-icon">keyboard_arrow_right</i></li>


            <li class="active">Контакты</li>

          </ul><!-- /.breadcrumb -->
        </div><!-- /.container -->
      </div><!-- /.content-title -->


      <div class="container">
        <div class="row">
          <div class="col-md-8 col-lg-9">
            <div class="content">
              <div class="container push-top-bottom">
                <div class="post-detail">
                  <%= Contact.last.text.html_safe %>

                  <h2>Связаться с нами!</h2>

                  <div class="comment-create clearfix">
                    <%= form_for(Form.new) do |f| %>
                    <div class="form-group">
                      <label>Сообщение</label>
                      <%= f.text_area :text,required: true, class: "form-control", rows: "5" %>

                    </div><!-- /.form-group -->

                    <div class="row">
                      <div class="col-sm-4">
                        <div class="form-group">
                          <label>Ваше имя</label>
                          <%= f.text_field :name,required: true, class: "form-control" %>

                        </div><!-- /.form-group -->
                      </div><!-- /.col-* -->

                      <div class="col-sm-4">
                        <div class="form-group">
                          <label>Почта</label>
                          <%= f.email_field :email,required: true, class: "form-control", autofocus: true %>

                        </div><!-- /.form-group -->
                      </div><!-- /.col-* -->
                    </div><!-- /.row -->

                    <div class="form-group-btn">
                      <%= f.submit "Отправить", class:"btn btn-primary btn-large pull-right" %>

                    </div><!-- /.form-group-btn -->
                    <%end%>
                  </div><!-- /.comment-create -->
                </div><!-- /.post-detail -->
              </div><!-- /.container -->
            </div><!-- /.content -->
          </div><!-- /.col-* -->

          <div class="col-md-4 col-lg-3">
            <div class="sidebar">
             <%= render 'petitions/widget' %>


              <div class="widget">
                <h2 class="widgettitle">Навигация</h2>

                <ul class="menu nav nav-stacked">
                  <li class="nav-item">
                    <a href="/" class="nav-link">Главная</a>
                  </li>

                  <li class="nav-item">
                    <a href="/categories" class="nav-link">Категории</a>
                  </li>

                  <li class="nav-item">
                    <a href="/contact" class="nav-link">Контакты</a>
                  </li>

                  <li class="nav-item">
                    <a href="/about" class="nav-link">О проекте</a>
                  </li>
                </ul><!-- /.nav -->
              </div><!-- /.widget -->
            </div><!-- /.sidebar -->
          </div><!-- /.col-* -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /.main-inner -->
  </div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/home/index.html.erb
<div class="main-wrapper">
  <div class="main">
      <div class="main-inner">


          <div class="content">
              <div class="hero" style="background-image: url('<%= image_path('img/tmp/cover-min.png'); %> ">
<div class="hero-content">
<div class="container">
  <h1>Платформа для содействия в реализации гражданами своих прав</h1>

  <p>
  Гражданское общество обретает силу в сплочённости. Поддержите проект, сообщите о нём своим знакомым. Вместе мы сделаем больше, чем каждый по отдельности!

  </p>

  <a href="/about" class="btn btn-primary">Распространить</a>
</div><!-- /.container -->
</div><!-- /.hero-content -->


<div class="hero-form ">
<div class="container">

  <%= form_tag search_path, :method => 'get' do %>
  <p>
    <div class="input-group col-sm-12 col-md-10">
      <div class="input-group-addon">
        <i class="md-icon">search</i>
      </div><!-- /.input-group-addon -->
    <%= text_field_tag :search, params[:search], type:"text", class:"form-control", placeholder:"Поиск..." %>
    </div>
    <div class="form-group last col-sm-12 col-md-2">
    <%= submit_tag "Поиск", :name => nil, class:"btn btn-primary btn-block" %>
    </div><!-- /.col-* -->
  </p>
<% end %>



</div><!-- /.container -->
</div><!-- /.hero-form -->

<div class="hero-layer"></div>
</div><!-- /.hero -->

<div class="container">
<div class="page-title">
<h2>Последние публикации</h2>

</div><!-- /.page-title -->

<div class="row">
<div class="col-sm-12 col-xl-10">
  <div class="cards-wrapper">
    <div class="row">
      <% Petition.where(status: 2).last(6).reverse_each do |p|  %>
        <div class="col-sm-6 col-md-4">
          <div class="card">
<div class="card-image" style="background-image: url('<%= image_path p.foto.url %>');">
<a href="<%= petition_path(p) %>"></a>


</div><!-- /.card-image -->

<div class="card-content">
<h3><a href="<%= category_path(p.category) %>"><%= p.category.name %></a></h3>
<h2><a href="<%= petition_path(p) %>"><%= p.name %></a></h2>
</div><!-- /.card-content -->

<div class="card-actions">
<% if user_signed_in? %>
<%= link_to add_petition_path(p), { method: :put , class: "card-action-icon", id: "like",remote: true} do %>
<i class="md-icon">favorite</i>
<%end%>
<%= p.like.users.count %>
<% else %>
<a href="<%= new_user_session_path %>" class="card-action-icon"><i class="md-icon">favorite</i></a><%= p.like.users.count %>
<%end%>
<a href="<%= petition_path(p) %>" class="card-action-btn btn btn-transparent">Далее</a>
</div><!-- /.card-actions -->
</div><!-- /.card -->
        </div><!-- /.col-* -->
<% end %>


    </div><!-- /.row -->
  </div><!-- /.card-wrapper -->
</div><!-- /.col-* -->

<div class="col-sm-2 hidden-lg-down">
  <div class="your-space">
    <p>
      <%= Ad.last.text.html_safe %>
    </p>

   
  </div><!-- /.your-space -->
</div><!-- /.col-* -->
</div><!-- /.row -->
</div><!-- /.container -->

<div class="container">
<div class="page-title">
<h2>Категории</h2>
</div><!-- /.page-title -->

<div class="cards-wrapper">
<div class="row">
  <% Category.all.each do |c| %>
    <div class="col-xs-12 col-sm-6 col-lg-3">
      <div class="card">
        <div class="card-image small no-line" style="background-image: url('<%= image_path c.foto.url %>');">
          <a href="<%= category_path(c) %>"></a>


          <div class="card-image-count">
          
            <strong><%=  c.petitions.where(status: 2).count  %></strong>
          
            <span>публикаций</span>
          </div><!-- /.card-image-count -->
        </div><!-- /.card-image -->

        <div class="card-content">
          <h2>
            <a href="<%= category_path(c) %>"><%= c.name %></a>

            <a href="<%= category_path(c) %>" class="btn btn-transparent">Далее</a>
          </h2>
        </div><!-- /.card-content -->
      </div><!-- /.card -->
    </div><!-- /.col-* -->
    <% end %>

</div><!-- /.row -->
</div><!-- /.cards-wrapper -->
</div><!-- /.container -->


<div class="cta">
<div class="container">
<h2>Проект «Власть Народа»</h2>

<p>запущен с целью предоставления сознательной части российского общества реального и легитимного инструмента взаимодействия с представителями местной, региональной и федеральной власти. Для консолидации гражданского общества, для взаимовыручки.</p>
<p>Мы верим, что совместными усилиями можно решить многие проблемы!</p>
<a href="/about" class="btn btn-primary">Далее</a>
</div><!-- /.container -->
</div><!-- /.cta -->

          </div><!-- /.content -->
      </div><!-- /.main-inner -->
  </div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/home/lk.html.erb
<h1>Home#lk</h1>
<p>Find me in app/views/home/lk.html.erb</p>

app/views/home/moderators.html.erb
<div class="container-fluid">
<div class="admin-title">
	<h1>Модераторы</h1>
<ul class="breadcrumb">
	<%= render_breadcrumbs :separator => '<i class="md-icon">keyboard_arrow_right</i>' %>
</ul>
</div>
</div>


<div class="admin-box no-padding">
	<table class="table small-header" id="table" >
		<thead>
			<tr>
				<th>Фото</th>
				<th>Роль</th>
				<th>Имя</th>
				<th>Фамилия</th>
				<th>Почта</th>
				<th>Телефон</th>
				<th>Дата Регистрации</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
        <% @users.reverse_each do |u| %>
				<tr>
					<td class="min-width">
						<div class="user-avatar">
							<%= image_tag u.foto.url  %>
						</div><!-- /.user-avatar -->
					</td>
					<td><%= u.role.name.first %></td>
					<td><%= u.name %></td>
					<td><%= u.father_name %></td>
					<td><%= u.email %></td>
					<td><%= u.tel %></td>
					<td><%= u.created_at.to_date %></td>

					<td class="min-width">
            <%= link_to  edit_user_path(u) do %>
            <i class="md-icon">edit</i>
            <% end %>
            <%= link_to  u, method: :delete, data: { confirm: 'Are you sure?' }   do %>
            <i class="md-icon">delete</i>
            <% end %>

					</td>
				</tr>
<% end %>

		</tbody>
	</table><!-- /.table -->
<nav class="pagination-wrapper">

	<%= paginate @users %>

</nav>
</div><!-- /.admin-box -->

app/views/home/page.html.erb
<div class="container-fluid">
<div class="admin-title">
	<h1>Категории</h1>
<ul class="breadcrumb">

</ul>
</div>
</div>


<div class="admin-box no-padding">
	<table class="table small-header">
		<thead>
			<tr>
				<th class="min-width">Фото</th>
				<th>Название</th>
			
				<th></th>
			</tr>
		</thead>

		<tbody>
      <% @categories.reverse_each do |p| %>
				<tr>

					<td class="min-width"><%= image_tag p.foto.url(:thumb) , class: "backend-table-thumb "%></td>
					<td><%= p.name %></td>
					
						</td>
						<td>
            <%= link_to p do %>
            <i class="md-icon">remove_red_eye</i>
            <% end %>


            <%= link_to edit_category_path(p) do %>
            <i class="md-icon">edit</i>
            <% end %>
						<%= link_to p, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="md-icon">delete</i>
            <% end %>



					</td>
				</tr>
        <% end %>
      </tbody>
</table>

</div><!-- /.admin-box -->

<nav class="pagination-wrapper">

	<%= paginate @categories %>

</nav>

app/views/home/partner.html.erb
<div class="main-wrapper">
  <div class="main">
    <div class="main-inner">

      <div class="content-title">
        <div class="container">
          <h1><%= @partner.title %></h1>
          <!-- <div class="social-share-about">
            <script type="text/javascript" src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" charset="utf-8"></script>
            <script type="text/javascript" src="//yastatic.net/share2/share.js" charset="utf-8"></script>
            <div class="ya-share2" data-services="vkontakte,facebook,odnoklassniki,moimir,gplus,twitter,lj,pocket,tumblr,viber,whatsapp" data-title="О проекте" data-description="<%= simple_format(@partner.text) %>"></div>
          </div> -->
          <ul class="breadcrumb">
            <li><a href="/">Главная</a> <i class="md-icon">keyboard_arrow_right</i></li>


            <li class="active">Партнёры</li>

          </ul><!-- /.breadcrumb -->
        </div><!-- /.container -->
      </div><!-- /.content-title -->


      <div class="container">
        <div class="row">
          <div class="col-md-8 col-lg-9">
            <div class="content">
              <div class="container push-top-bottom">
                <div class="post-detail">
                  <%= @partner.text.html_safe %>

                  <div class="">
                    <form method="post" action="">
                      <div class="row">
                        <div class="col-sm-4">
                        </div><!-- /.col-* -->

                        <div class="col-sm-4">
                        </div><!-- /.col-* -->
                      </div><!-- /.row -->

                    </form>
                  </div><!-- /.comment-create -->
                </div><!-- /.post-detail -->
              </div><!-- /.container -->
            </div><!-- /.content -->
          </div><!-- /.col-* -->

          <div class="col-md-4 col-lg-3">
            <div class="sidebar">
            <%= render 'petitions/widget' %>


              <div class="widget">
                <h2 class="widgettitle">Навигация</h2>

                <ul class="menu nav nav-stacked">
                  <li class="nav-item">
                    <a href="/" class="nav-link">Главная</a>
                  </li>

                  <li class="nav-item">
                    <a href="/categories" class="nav-link">Категории</a>
                  </li>

                  <!-- <li class="nav-item">
                    <a href="/partners" class="nav-link">Партнёры</a>
                  </li> -->
                  <li class="nav-item">
                    <a href="/contact" class="nav-link">Контакты</a>
                  </li>

                  <li class="nav-item">
                    <a href="/about" class="nav-link">О проекте</a>
                  </li>
                </ul><!-- /.nav -->
              </div><!-- /.widget -->
            </div><!-- /.sidebar -->
          </div><!-- /.col-* -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /.main-inner -->
  </div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/home/search.html.erb
<div class="main-wrapper">
	<div class="main">
		<div class="main-inner">

			<div class="content-title">
				<div class="container">
					<h1>Поиск</h1>



					<ul class="breadcrumb">
						<li><%= render_breadcrumbs :separator => '<i class="md-icon">keyboard_arrow_right</i>' %></li>




					</ul><!-- /.breadcrumb -->
				</div><!-- /.container -->
			</div><!-- /.content-title -->


			<div class="container">
				<div class="row">
					<div class="col-md-8 col-lg-9">
						<div class="content">
							<div class="container push-top-bottom">
								<div class="posts">

									<% @petitions.each do |p| %>
									<div class="post">
										<div class="post-date">
											<strong><%= p.created_at.day %></strong>
											<span><%= l(p.created_at, format: '%b') %></span>
										</div>

										<div class="post-image">
											<a href="<%= category_petitions_path(p.category, p) %>" class="post-image-link" style="background-image: url('<%= image_path p.foto.url %>');"></a>

											<div class="post-author">
												<span class="post-author-image">
													<a href="#" style="background-image: url('<%= p.user.foto.url %>');"></a>
												</span><!-- /.post-author-image -->

												<a href="<%= category_petitions_path(p.category, p) %>">
													<span class="post-author-name"><%= p.user.name %></span>
												</a>
											</div><!-- /.post-author -->
										</div><!-- /.post-image -->

										<div class="post-title">
											<h2><a href="<%= category_petitions_path(p.category, p) %>"><%= p.name %></a></h2>
										</div><!-- /.post-title -->



										<div class="post-content">
											<p>
												<%= truncate(p.text, length: 1000, escape: false) %>
											</p>
										</div><!-- /.post-content -->

										<div class="post-read-more">
											<a href="<%= category_petitions_path(p.category, p) %>">Подробней <i class="fa fa-chevron-right"></i></a>
										</div><!-- /.post-read-more -->
									</div><!-- /.post-->
									<% end %>

								</div><!-- /.posts-->
								<nav class="pagination-wrapper">

									<%= paginate @petitions %>

								</nav>

							</div><!-- /.container -->
						</div><!-- /.content -->
					</div><!-- /.col-* -->

					<div class="col-md-4 col-lg-3">
						<div class="sidebar">
							<%= render 'petitions/widget' %>
							<%= render 'categories/widget' %>
						</div><!-- /.sidebar -->
					</div><!-- /.col-* -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</div><!-- /.main-inner -->
	</div><!-- /.main -->
</div><!-- /.main-wrapper -->

app/views/home/vote.html.erb
<div class="container-fluid">
<div class="admin-title">
	<h1>Петиции</h1>
<ul class="breadcrumb">

</ul>
</div>
</div>


<div class="admin-box no-padding">
	<table class="table small-header">
		<thead>
			<tr>
				<th class="min-width">Фото</th>
				<th>Название</th>
				<th>Категория</th>
				<th>Автор</th>
				<th>Статус</th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
      <% @petitions.each do |p| %>
				<tr>

					<td class="min-width"><%= image_tag p.foto.url(:thumb) , class: "backend-table-thumb "%></td>
					<td><%= p.name %></td>
					<td><%= p.category.name %></td>
					<td><%= p.user.name %> <%= p.user.surname %></td>
						<td><%= p.status.name %>

							<% if p.status_id == 1 %>
							<%= link_to 'опубликовать', st_petition_path(p), { method: :put, id: 'push' } if current_user.role_id == 1 %>
							<% end %></td>
					<td>
						</td>
						<td>
            <%= link_to p, class: 'btn btn-red' do %>
            <i class="md-icon">remove_red_eye</i> Просмотреть
            <% end %>



					</td>
				</tr>
        <% end %>
      </tbody>
</table>

</div><!-- /.admin-box -->

<nav class="pagination-wrapper">

	<%= paginate @petitions %>

</nav>