config/routes.rb
Rails.application.routes.draw do
 

  resources :responses
  devise_for :users
  resources :users 
  
  

  # resources :surveys 
  
  # resources :questions
  # resources :answers
  # resources :responses

  resources :ads
  resources :abouts
  resources :contacts
  resources :forms
  resources :pages

  get '/search' =>  'home#search'

  get '/contact' => 'home#contact'

  get '/about' =>  'home#about'
  get '/partners' =>  'home#partner'

  get '/lk' =>  'home#lk'
  get '/vote' =>  'home#vote'
  get '/admin_category' =>  'home#page'

  get '/moderators' =>  'home#moderators'
  get '/admins' =>  'home#admins'

  
  resources :categories
  
  resources :petitions do
    member do
      put 'vote'
      put 'st'
      put 'add'
    end
  end
  get '/categories/:category_id/:id' => 'petitions#categories', as: :category_petitions
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, :to => :crud
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.moder?
        can :manage, Petition
        can :read, Category
        cannot :vote , Petition
        can :update, User do |u|
   u.try(:user) == user
                          end  
   elsif user.user?
     can :read , Petition
     can :read , Category
     can :update, User do |u|
u.try(:user) == user
                        end
     can :update, Petition do |u|
u.try(:user) == user
                            end
    elsif user
    can :read , all
   
   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :response_answers, dependent: :destroy
	has_many :response_questions, through: :response_answers
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :petitions, dependent: :destroy
  before_destroy :des
  before_create :assign_slug
  before_update :assign_slug

  has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/

  def to_param
    "#{slug}"
  end

  def assign_slug
    self.slug = self.name.to_slug_param(locale: :ru)
  end

  def des
    self.foto = nil
    self.save
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/form.rb
class Form < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
	has_many :users
end

app/models/page.rb
class Page < ActiveRecord::Base
	before_destroy :des
	before_create :assign_slug
	before_update :assign_slug
	validates :name , uniqueness: { case_sensitive: false }
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	def to_param
		"#{slug}"
	end

	def assign_slug
		self.slug = self.name.to_slug_param(locale: :ru)
	end

	def des
		self.image = nil
		self.save
	end



end

app/models/petition.rb
class Petition < ActiveRecord::Base
  #assiciations
  belongs_to :status
  belongs_to :vote
  belongs_to :like
  belongs_to :category
  belongs_to :user

  has_many :responses, dependent: :destroy
  has_many :users, through: :responses
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: lambda { |a| a[:text].blank? }, allow_destroy: true

  #Callbacks
  before_create :vot
  before_create :add
  before_save :st
  before_create :assign_slug
  before_update :assign_slug
  before_destroy :des

  #Methods
  def des
    self.foto = nil
    self.save
  end
  def vot
    self.vote = Vote.create
  end
  def add
    self.like = Like.create
  end
  def st
    self.status = Status.find(1) if self.status.nil?
  end

  # def slug
  #   name.mb_chars.downcase.gsub(" ", "-").to_s  
  # end
  def assign_slug
    self.slug = self.name.to_slug_param(locale: :ru)
  end

  def to_param 
   "#{slug}"
 end

 has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
 validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/


 def self.search(search)
  if search
    self.where("name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ?", "%#{search.mb_chars.capitalize.to_s}%", "%#{search.mb_chars.to_s}%", "%#{search.mb_chars.upcase.to_s}%", "%#{search.mb_chars.downcase.to_s}%" )
  else
    self.all
  end
end
end

app/models/post.rb
class Post < ActiveRecord::Base


    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
     validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :petition
	has_many :response_questions, dependent: :destroy
	has_many :responses, through: :response_questions
	has_many :answers, dependent: :destroy
	accepts_nested_attributes_for :answers, reject_if: lambda { |a| a[:text].blank? }, allow_destroy: true

end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :user
	belongs_to :petition
	has_many :questions, through: :response_questions
	has_many :response_questions, dependent: :destroy
	accepts_nested_attributes_for :response_questions, allow_destroy: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, dependent: :destroy
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :petitions , dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :petitions, dependent: :destroy
  belongs_to :role
  belongs_to :like
  has_and_belongs_to_many :vote
  has_many :responses, dependent: :destroy
  # has_many :petitions, through: :responses
  # has_many :petitions


  before_destroy :des

  has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/

  scope :admin?, -> {where(role_id: 1)}

  def des
    self.foto = nil
    self.save
  end

 #  def to_param
 #   "#{name}"
 # end
 before_save :assign_role
 def assign_role
  self.role = Role.find_by name: "Пользователь" if self.role.nil?
end
def admin?
  self.role.name == "Админ"
end
def moder?
  self.role.name == "Модератор"
end
def user?
  self.role.name == "Пользователь"
end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<title>Власть народа</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>
<body>

	<div class="admin-wrapper">
		<div class="admin-sidebar">
			<a href="<%=  %>" class="hidden-md-down">
				<h3> Личный Кабинет </h3>
			</a>

			<% if current_user.role_id == 1 %>
			<%= link_to "Добавить Категорию", new_category_path, class: "btn btn-primary btn-block hidden-md-down" %>
			<% else %>

			<%= link_to "Добавить Публикацию", new_petition_path, class: "btn btn-primary btn-block hidden-md-down" %>
			<% end %>

			<div class="dashboard-nav-primary collapse navbar-toggleable-md">
				<ul class="nav nav-pills nav-stacked">

					<% if current_user.id == 2 %>


					<li class="nav-item">
						<a href="<%= petitions_path %>" class="nav-link "><i class="md-icon">view_list</i> Публикации </a>
					</li>

					<li class="nav-item">
						<a href="<%= admin_category_path %>" class="nav-link "><i class="md-icon">view_list</i> Категории </a>
					</li>


					<li class="nav-item ">
						<a href="<%= admins_path %>" class="nav-link "><i class="md-icon">people</i> Администраторы</a>
						
					</li>
					<li class="nav-item ">
						<a href="<%= moderators_path %>" class="nav-link "><i class="md-icon">people</i> Модераторы </a>
						
					</li>
					<li class="nav-item ">
						<a href="<%= users_path %>" class="nav-link "><i class="md-icon">people</i> Пользователи </a>
						
					</li>
					<li class="nav-item">
						<a href="<%= edit_contact_path(Contact.last) %>" class="nav-link "><i class="md-icon">edit</i> Контакты</a>
					</li>
					<li class="nav-item">
						<a href="<%= edit_about_path(About.last) %>" class="nav-link "><i class="md-icon">edit</i> О проекте </a>
					</li>
					<li class="nav-item">
						<a href="<%= edit_ad_path(Ad.last) %>" class="nav-link "><i class="md-icon">edit</i> Реклама </a>
					</li>
					<li class="nav-item">
						<a href="<%= edit_page_path(Page.find_by(name: "Партнёры")) %>" class="nav-link "><i class="md-icon">edit</i> Партнёры </a>
					</li>

					<% elsif current_user.role_id == 1 or 3   %>

					<li class="nav-item">
						<a href="<%= petitions_path %>" class="nav-link "><i class="md-icon">view_list</i> Публикации </a>
					</li>


					<% elsif current_user.role_id == 2 %>

					<li class="nav-item">
						<a href="<%= petitions_path %>" class="nav-link "><i class="md-icon">view_list</i> Мои Публикации </a>
					</li>
					

					<li class="nav-item">
						<a href="<%= vote_path %>" class="nav-link "><i class="md-icon">people</i> Мои Голоса </a>
					</li>

					<% end %>
					<li class="nav-item">
						<a href="<%= edit_user_path(current_user) %>" class="nav-link "><i class="md-icon">edit</i> Профиль </a>
					</li>
					<li class="nav-item">

						<%= link_to destroy_user_session_path, :method => :delete, class: "nav-link" do %>
						<i class="md-icon">power_settings_new</i> Выход
						<% end %>
					</li>
				</ul>
			</div>

			<hr class="hidden-md-down">

		</div><!-- /.admin-sidebar -->

		<div class="admin-main">
			<div class="admin-header">
				<div class="admin-header-navigation">
					<div class="container-fluid">
						<ul class="nav nav-pills">
							<li class="nav-item"><a href="/" class="nav-link">Главная</a></li>


							<li class="nav-item"><a href="/categories" class="nav-link">Категории</a></li>

							<li class="nav-item"><a href="/contact" class="nav-link">Контакты</a></li>
							<li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
						</ul>
						<% if user_signed_in? %>
						<ul class="nav nav-pills secondary">

							<li class="nav-item user-avatar-wrapper hidden-sm-down">

								<a href="#" class="nav-link circle user-avatar-image" style="background-image: url('<%= current_user.foto.url %>')"></a>
								<span class="user-avatar-status"></span>

								<ul class="header-more-menu">
									<% if current_user.role_id == 1 or 3 %>
									<li><%= link_to "Публикации", petitions_path %></li>
									<%else%>
									<li><%= link_to "Мои Публикации", petitions_path %></li>
									<% end %>
									<li><%= link_to "Редактировать", edit_user_path(current_user) %></li>
									<li><%= link_to "Выход", destroy_user_session_path, :method => :delete %></li>
								</ul>
							</li>
						</ul>
						<% end %>
						<button class="navbar-toggler pull-xs-right hidden-lg-up" type="button" data-toggle="collapse" data-target=".dashboard-nav-primary">
							<i class="md-icon">menu</i>
						</button>
					</div><!-- /.container -->
				</div><!-- /.admin-header-navigation -->
			</div><!-- /admin-header -->

			<%= render :partial => 'home/error', :flash => flash %>
			<%= yield %>
		</div>
	</body>
	</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>Власть народа</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="page-wrapper">
  <div class="header-wrapper">
  	<div class="header">
  		<div class="header-inner">
  			<div class="header-top">
  				<div class="container">
  					<a href="/">
            <%= image_tag "/assets/img/logo_main.png", class: "header-top-logo" %>
  						<!-- <img src="/public/assets/img/logo_main.png" alt="" class="header-top-logo"> -->
  					</a>

  					<div class="nav-primary-wrapper collapse navbar-toggleable-sm" aria-expanded="true">
  						<ul class="nav nav-pills ">
                <li class="nav-item has-submenu"><a href="/" class="nav-link">Главная</a></li>
                <li class="nav-item has-submenu"><a href="/categories" class="nav-link">Категории</a></li>
                <li class="nav-item has-submenu"><a href="/contact" class="nav-link">Контакты</a></li>
                <li class="nav-item has-submenu"><a href="/about" class="nav-link">О проекте</a></li>
  						</ul><!-- /.nav -->
  					</div><!-- /.nav-primary-wrapper -->


  					<ul class="nav nav-pills secondary">

<% if user_signed_in? %>
  						<li class="nav-item user-avatar-wrapper">
  							<a href="<%= petitions_path %>" class="nav-link circle user-avatar-image" style="background-image: url('<%= current_user.foto.url %>')"></a>
  							<span class="user-avatar-status"></span>

  							<ul class="header-more-menu">
                <% if current_user.role_id == 1 or current_user.role_id ==3  %>
                  <li><%= link_to "Публикации", petitions_path %></li>
                <%else%>
                  <li><%= link_to "Мои Публикации", petitions_path %></li>
                  <% end %>
                  <li><%= link_to "Редактировать", edit_user_path(current_user) %></li>
  								<li><%= link_to "Выход", destroy_user_session_path, :method => :delete %></li>
                  <% else %>
                  <li class="nav-item"><%= link_to "Регистрация", new_user_registration_path,class: "nav-link" %></li> <li class="nav-item"> <%= link_to "Вход", new_user_session_path,class: "nav-link" %></li>


  							</ul>
  						</li>
              <% end %>
  					</ul>


  					<button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target=".nav-primary-wrapper">
                          <i class="md-icon">menu</i>
                      </button>

					  <button class="navbar-toggler pull-xs-right hidden-md-up" type="" data-toggle="" data-target=".nav-primary-wrapper">
                          <%= link_to new_user_session_path do %><i class="md-icon">vpn_key</i> <% end %>
                      </button>

  				</div><!-- /.container -->
  			</div><!-- /.header-top -->


  				<div class="header-bottom">
  					<div class="container">
  						<div class="header-bottom-label hidden-md-down">
  							<a href="/categories">Категории</a>
  						</div><!-- /.header-bottom-label -->
              <% Category.last(7).each do |c| %>
  						<ul class="nav nav-pills">


  							<li class="nav-item"><%= link_to c.name, c , class: "nav-link"  %></li>
  						</ul><!-- /.nav -->
              <% end %>


  					</div><!-- /.container -->
  				</div><!-- /.header-bottom -->

  		</div><!-- /.header-inner -->
  	</div><!-- /.header -->
  </div>
<%= render :partial => 'home/error', :flash => flash %>
<%= yield %>

<div class="footer-wrapper">
 <div class="footer">
   <div class="footer-widgets">
     <div class="container">
       <div class="row">
         <div class="col-xs-12 col-sm-12 col-md-3">
           <div class="widget right-border">
             <h2 class="widgettitle"><%= image_tag "/assets/img/logo_main.png" %></h2>
			 <p>Проект «Власть Народа» - это платформа для содействия в реализации гражданами своих прав.<br>Петиции, Инициативы, Содействие, Опросы.</p>

           </div><!-- /.widget -->
         </div><!-- /.col-* -->

         <div class="col-xs-12 col-sm-12 col-md-2 col-md-offset-1">
           <div class="widget right-border">
             <h2 class="widgettitle">Мы в интернете</h2>

             <ul class="nav nav-stacked">
               <li class="nav-item"><a href="#" class="nav-link">Facebook</a></li>
               <li class="nav-item"><a href="#" class="nav-link">Вконтакте</a></li>
               <li class="nav-item"><a href="#" class="nav-link">Одноклассники</a></li>
               <li class="nav-item"><a href="#" class="nav-link">Twitter</a></li>
             </ul>
           </div><!-- /.widget -->
         </div>

         <div class="col-xs-12 col-sm-12 col-md-2 col-md-offset-1">
           <div class="widget right-border">
             <h2 class="widgettitle">Разделы</h2>

             <ul class="nav nav-stacked">
               <li class="nav-item"><a href="/" class="nav-link">Главная</a></li>
               <li class="nav-item"><a href="/categories" class="nav-link">Категории</a></li>
               <li class="nav-item"><a href="/contact" class="nav-link">Контакты</a></li>
               <li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
             </ul>
           </div><!-- /.widget -->
         </div><!-- /.col-* -->

         <div class="col-xs-12 col-sm-12 col-md-2 col-md-offset-1">
           <div class="widget">
             <h2 class="widgettitle">Партнёры</h2>

             <ul class="nav nav-stacked">
               <li class="nav-item"><a href="http://nabludatel.org/" class="nav-link">Гражданин Наблюдатель</a></li>
               <li class="nav-item"><a href="http://www.golosinfo.org/" class="nav-link">ГОЛОС</a></li>
               <li class="nav-item"><a href="http://sonarus.org/" class="nav-link">СОНАР</a></li>
               <li class="nav-item"><a href="http://www.dissernet.org/" class="nav-link">ДИССЕРНЕТ</a></li>
             </ul>
           </div><!-- /.widget -->
         </div><!-- /.col-* -->
       </div><!-- /.row -->
     </div><!-- /.container -->
   </div><!-- /.footer-widgets -->

   <!--<div class="footer-top">
     <div class="container">
       <div class="footer-top-left">
         <strong class="hidden-xs-down">Supported credit cards:</strong>
         <i class="fa fa-cc-stripe"></i>
         <i class="fa fa-cc-visa"></i>
         <i class="fa fa-cc-discover"></i>
         <i class="fa fa-cc-mastercard"></i>
       </div><!-- /.footer-top-left -->

      <!-- <div class="footer-top-right">
         <a class="footer-top-action">
           <i class="md-icon">vertical_align_top</i>
         </a><!-- /.footer-top-action -->

         <!--<ul class="nav nav-pills">
           <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
           <li class="nav-item"><a class="nav-link" href="#">Pricing</a></li>
           <li class="nav-item"><a class="nav-link" href="#">FAQ</a></li>
           <li class="nav-item"><a class="nav-link" href="#">About Us</a></li>
         </ul>
       </div><!-- /.footer-top-right -->
    <!-- </div><!-- /.container -->
   <!--</div><!-- /.footer-top -->

   <div class="footer-bottom">
     <div class="container">
       <div class="footer-bottom-left">
      Developed by &nbsp;<a href="http://digilab.pro"><img src="<%= image_path('img/digilab.png') %>" class="digilab-logo-footer"></a>
       </div><!-- /.footer-bottom-left -->

       <div class="footer-bottom-right">
         Copyright &copy; 2016 - Все права защищены
       </div><!-- /.footer-bottom-right -->
     </div><!-- /.container -->
   </div><!-- /.footer-bottom -->
 </div><!-- /.footer -->
</div><!-- /.footer-wrapper -->
</div>
</body>
</html>